name: Laravel

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Build Container and Push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
      
